language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: "rlqIlyqFrYrS2jNuVIlGY6juNIHb5mH67TwKiJqPj5virue2ZEisXMU4ydgiQQgykqQurhan2G6r3cDxDc5win7ywz0TwY5P4Lfo9QL5vNDdl6k7vF7lSPMhcyDMRSJXbM5HhPJQBsW68/lWCguc8UUtPRJ4sXqzEWXCmminGfWCiDDRmytaBeom2egTpBgb1s82pYeucCVf8OBEyA/giw1r/c9EbGU1HorL17nXbsupDI/Jd/6t0A3c6ViCvLke1ulMJU40Hx0ueWSrHDEjFBKxA7tvhN2OTJ7nAyEdc4lvWwbzx1cwHLRGuwxlX30Twrh07xMR5vUv9ZRHZHYtE29F4hrxyEtqmSHofF+gGhIMGeyLqzDtMhVMucfBKAFkvP/FxCTSpXyohewTTKN/phliunB0CkHwFCChKxfa5W6mIji0w87myxjoSGEFOlFPT089Ixfm9GwP6xuiTjjq7DheeyZBo0MWDMDzd89VERCCT1pbVGwhysGMcEWic+c9a+owp2gt/GNnpcgx9/nR+FHBwp7FLD8gqZBIjQSfAQXxyioRELpzsCRJK7iRrMFTnEV/4jXqDVfzAzc9piXKQZKvarMHfqH3b1A5G776n8vnqIlyIo2OC5nW7w+xGfy5KRY6NiDcpUuq/8OVxOr/cRdLivWYGv/TVdQ5qO0M4hA="
  - secure: "PAyzLOsW71/GmMztfg49u0e9TvfjT58b5XlfOJsnO68U08LW5ukD7po454+hcf7O08bKPXuRTSLaCkeNkftyvfIh7As+a5aT9hrWuXBZqxJlP4qxUQTdYhBBW41YLroPtj53bLvyosVEP5iITvOasSmAVOHnawtkqMrRTTYhckIB3uWGe3CCgFRezxq54vaAeNBxPr/KqCOwnJ+BGsJNLtOTah/bpVRWQYsyl5QsXM1pEDDyWvzkme1CjvLnxSUG9C3GIjQUW3wj0ebGsYQvcTfnFF84kt8JKHSlw5FZX69Y0VOK4K9GkSp6TQvjkl3XSlmcEeBhrqnD0xR0ci/B6v4BpkmNBkGSMFLRAVZGtkicWLfPazPWqSNifO4Je215WRpwTUgsYAoigN2k+mwwDRSgE+ypnJ8yF3vfGOCoV3vQboyyPLOVZ2PBU9zNEaEHaDnhOO2blyloa+PHD4tUPotWF6DqnC9PExj/4A3xT8UCdFUZTsNeBhN1hXVNZg7XZJdGf7wXwiHymI5ee3N/oe4ZK4reO30uCG1s5ZjaYXkbGnGGKJoA5hAzMXafTk89TtGFGivMXPSIy+PKc7TShmZZePOSKVMKsIfVJ/ctOo/QPQEdhRGyzTLTcIlm0P5nXkgVq0nWPmbt37GDLiZu0GQTw+eRuHB8HbSEjhHqxOg="
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: MNsW8Lg1YIhm8V0YqzuzV+Uwllg6TFWllfAnSzbllonFRMJpwM1g3aO9GLlP2WcbmbLBWk0BolYa2o7DQSUxcq/Vvv4RWZTdrSLnNRHKczbI8PhQRy+/NyOqOSXAZ2ZVVYDKTnq3DYZsWl3sUnML+iClkAUSDnH8dxUyPnoTkcYE4t1HqLhOg1dkAtIUolJ7sIXdjeHadzWhFQsn+qVxyXgcw0NwmpIo9zQlHwwLvIjMpL+Z3CfPHaNWyZ0WpshFZSDjFJ+39BOAYSoTm3HQS2ZYVk4c1B/Ss3jaJS+BPT2gnsKeNnX+URFMDz7R7GDOEq85cBZuSwdZif6YtsoSfyB44/3o33Bl7svZ7TAoaZbRRMndj/DQ+qZLdoOuLc1D4nPrN8bsIiX0BOD8gxZas53IOgCFTo2csUJV5HpOFhBu8WEFVJn7Lf+LxQtZBtmLEUN0NpG5Rp47lnc6pg09wIi6LMEEHY1st1RFctAibIEjpMtfqWamONWXOsuLOBT96BAroeTqAsHDceWafQUeWPqaBWT5RfCPw974todrhoPPSwIp+00I0n/r73LjHT0ddXvHn52zmY9KWHN8Jeleoj942n1DNNzy4yUHUVJH4EjMKFg+AU2FWzQMHSDEmspOakohvLaPZquJxhqnZkxpcwydJbbNjWcFSOVCJJgk+5E=
  on:
    branch: master
    repo: plepers/nanogl-renderer
