language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: "lXhT+rZHfpjWbDfC88NM31zf7syMrFwLGS6d7gJERcr9P0W403NLS1JRGlFuBnll7Xdo2fxp3v4GZzvugQQ0n1u8KfwtAooap5Eq8i7/+nVFgKM9A8nIqs1kR1zBROjbm4NmYR8bEKmKxAJx0CwAtG2iURoxVHjCBogjaEwQiqVA9UpT0F77Js2Y0gl2TYwlanQqb905Eo7EcavCkIcdcadp8gpLL63wVg28OrY5mQ6Hmq8OA9uAArmY1LV12yMHvo4AKA5K9i0vADhGVxg9mEE2MF8kv+e4GdaVDM2ZHcRBVGtQQt8e/d5p/1+itMdh2YQoGvsSdZ9KLeNELkdbjlNzmgoLY4ptiYc1D0C9A0qwmeAWeJuT58RPtXz8jC32M6oNmq3QavWIlA3Jzu4M+NnBdbSTDz8DiguIlVbgBxC2zrO/JdZRnYdjEhGeAfKZE2mYY03jMqBO1in+D66sgo/zjsQuIdrHWoMZyTtBcdmqVEGqM1YXVmLKlyZamF7jYop7/LMC82SzCXH5TSmErM/gIiIKvhLDQELY6wAbgln9z9ji0qUSsydkLrtV5Djqs5Urz3dlY8oodjx2Kaar650+VtD8kuNcunlWqD+NXvpXIy1bX4m/q02BGiSYV8+vQexTVtyq0nWowRz3apJdIt7/nTN3dwVy1xGKFCK6e18="
  - secure: "WPuBpa3WrdfPIskoQV8GBEgE3+N0rNcKNdgLjI++/Y7GQl2NFW7WJAkjbpoYWvEMVkWUq/BQxOnI6nDyXNS1c+hDXwpCGql6F10Aon/HlH0eux56lUyEkzR58D2pQFDObp+d9IA9y/saCPoxqbdJ/1rl5p5u5ZvsojM9K/1GaPJ8j/kOUfLAQrjtsNzsoFrKgRgIe2YEYz0Cf5ufV3MI4+7siDty1ZLBbfjaV+24WqZfyuc+6dfHmlZCOZg6mZFdZpPfpCpYOTuiJ9F7cepUBdlIAGDBVOTUlaSUOtD3vzosXubqDZdlwN0VAeJTBwIZSpLZxdAfpz64i4WMsJ3ljlUVZufdMlGPquOGHYdZFpavmm+VHN3J33xBsyPrSbvoH+snvdNLa9zejLOkoJ1g9pqgALl39IJa5iAYKrKbZLUsgh5LH95bnIjTKIUHN8XVdOpZyAgFrwW+1d4WL7lVEvE2ecUtrlAxqqMxSYbou8GvDy4quXZGYELutBO9JKupx8QAb77f1rM1JZtL7eAE7K9vxgT0ky70fRvd5fKChzX90MLW2okFQICIx3w/9L7PiCavYiyMNyg86pL6IbJCPJRXb/F1hJo3L0FItZ5P0dCY+THYQp39LERIhkaLP90riz9iYt8sePXsxuC/xHcZbMX0AwYzAnpiORuPhYARc3c="
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: MNsW8Lg1YIhm8V0YqzuzV+Uwllg6TFWllfAnSzbllonFRMJpwM1g3aO9GLlP2WcbmbLBWk0BolYa2o7DQSUxcq/Vvv4RWZTdrSLnNRHKczbI8PhQRy+/NyOqOSXAZ2ZVVYDKTnq3DYZsWl3sUnML+iClkAUSDnH8dxUyPnoTkcYE4t1HqLhOg1dkAtIUolJ7sIXdjeHadzWhFQsn+qVxyXgcw0NwmpIo9zQlHwwLvIjMpL+Z3CfPHaNWyZ0WpshFZSDjFJ+39BOAYSoTm3HQS2ZYVk4c1B/Ss3jaJS+BPT2gnsKeNnX+URFMDz7R7GDOEq85cBZuSwdZif6YtsoSfyB44/3o33Bl7svZ7TAoaZbRRMndj/DQ+qZLdoOuLc1D4nPrN8bsIiX0BOD8gxZas53IOgCFTo2csUJV5HpOFhBu8WEFVJn7Lf+LxQtZBtmLEUN0NpG5Rp47lnc6pg09wIi6LMEEHY1st1RFctAibIEjpMtfqWamONWXOsuLOBT96BAroeTqAsHDceWafQUeWPqaBWT5RfCPw974todrhoPPSwIp+00I0n/r73LjHT0ddXvHn52zmY9KWHN8Jeleoj942n1DNNzy4yUHUVJH4EjMKFg+AU2FWzQMHSDEmspOakohvLaPZquJxhqnZkxpcwydJbbNjWcFSOVCJJgk+5E=
  on:
    branch: master
    repo: plepers/nanogl-renderer
